
version: '3'
services:
  app_main:
    container_name: frontend_admbus
    build: front/.
    environment:
      - DB_USER=admin
      - DB_PASS=admin
      - DB_NAME=adbus
      - DB_HOST=app_data
    ports:
      - "8080:80"
    deploy:
      replicas: 1
    depends_on:
      - app_data
    networks:
      - app_network

  app_data:
    container_name: backend_admbus
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: live123
      MYSQL_DATABASE: adbus
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
